name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build project
    runs-on: ubuntu-latest
    outputs:
      RUNNER: ${{ runner.name }}
    steps:
    - uses: actions/checkout@v3
    - name: make all
      run: make
    - name: run src
      run: ./src/aes
    - run: echo "selected runner = ${{ runner.name }}"
      
  test:
    name: run unit tests
    needs: build
    runs-on: ${{needs.build.outputs.RUNNER}}
    steps:
      - name: run tests
        run: ./tests/tests
