name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    name: build project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make all
      run: make
    - name: run src
      run: ./src/aes
       
  test:
    name: run unit tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: make all
      run: make
    - name: run unit tests
      run: ./tests/tests
